name: efada
description: A new Flutter project.

publish_to: 'none'

version: 2.4.0+33

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  google_maps_flutter: ^2.1.8
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.1
  qr_flutter:
  equatable: ^2.0.3
  file_picker: ^4.2.4
  file_utils: ^0.1.3
  change_app_package_name: ^1.1.0
  flutter_bloc: ^8.0.1
  flutter_calendar_carousel: ^2.4.1
  flutter_cupertino_date_picker_fork: 1.0.3
  flutter_cupertino_localizations: ^1.0.1
  flutter_local_notifications: ^8.1.1+1
  flutter_webview_plugin: ^0.4.0
  fluttertoast: ^8.0.8
  http: ^0.13.0
  open_file: ^3.2.0
  path_provider: ^2.0.1
  rxdart: ^0.26.0
  scoped_model: ^1.0.1
  shared_preferences: ^2.0.6
  uuid: ^3.0.0
  shimmer: ^2.0.0-nullsafety.0
  fancy_shimmer_image: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.3
  age: ^0.0.1
  intl: ^0.17.0
  flutter_overlay_loader: ^0.1.1
  flutter_cache_manager: ^3.0.0-nullsafety.1
  timeago: ^3.0.2
  flutter_slidable: ^0.6.0-nullsafety.0
  font_awesome_flutter: ^9.0.0
  pdf_flutter:
    git: https://github.com/emran92/pdf_flutter
  provider: ^6.0.0
  cached_network_image: ^3.0.0
  flutter_inappwebview: ^5.3.2
  extended_image: 3.0.0
  ffi: ^1.0.0
  firebase_core: ^1.17.0
  firebase_messaging: ^11.4.0
  flutter_dropdown_alert: ^1.0.1
  edge_alert: ^0.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_widget_from_html: ^0.7.0
  permission_handler: ^8.1.4+2
  http_auth: ^1.0.1
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  flutter_credit_card: ^3.0.0
  carousel_slider: ^4.0.0
  persistent_bottom_nav_bar: ^4.0.2
  device_info_plus: ^3.1.0
  package_info_plus: ^1.3.0
  get: ^4.6.5
  google_fonts: ^2.1.0
  badges: ^2.0.1
  themify_flutter: ^1.0.0
  stripe_sdk: ^5.0.0-nullsafety.1
  flutter_portal: ^0.4.0
  loading_more_list: ^4.0.1
  let_log: ^1.1.4
  emoji_picker_flutter: ^1.0.8
  flutter_easyloading: ^3.0.3
  photo_view: ^0.13.0
  better_player: ^0.0.77
  flutter_launcher_icons: ^0.9.0
  flutter_staggered_animations: ^1.0.0
  razorpay_flutter: ^1.2.7
  firebase_core_platform_interface: 4.5.1
  khalti: ^1.0.2
  reorderables:
    git: https://github.com/emran92/reorderables
  pusher_channels_flutter: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4
  import_sorter: ^4.6.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/config/app_icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/config/splash_logo.png
  fullscreen: true
  color: "FFFFFF"


flutter:
  uses-material-design: true
  assets:
   - assets/config/
   - assets/images/
   - assets/locale/

fonts:
  - family: popins
    fonts:
      - asset: fonts/poppins_medium.ttf
        weight: 100
      - asset: fonts/poppins_bold.ttf
        weight: 200
      - asset: fonts/poppins_light.ttf
        weight: 300
      - asset: fonts/poppins_regular.ttf
        weight: 400
      - asset: fonts/poppins_semibold.ttf
        weight: 500
